### ISSUE TITLE
Mystery interpolation in interpolq.f90

### ISSUE THREAD

**Issue by susilehtola** [susilehtola/x2dhf#20]
interpolq.f90 calls lpcoeffq in many places to generate interpolation coefficients, but it doesn't initialize the vmuq array anywhere that is used in lpcoeffq. Where is the data supposed to come from?

**Comment by jacekkobus** [comment]
From dointerp.f90 via commons16.f90.

**Comment by susilehtola** [comment]
But the code isn't used anymore, since the program only supports ngrids=1, right?

**Comment by jacekkobus** [comment]
interpolq.f90 is now redundant and has ben deleted.

**Comment by susilehtola** [comment]
That's what I thought, thanks!
