### ISSUE TITLE
fpw86 arguments broken

### ISSUE THREAD

**Issue by susilehtola** [susilehtola/x2dhf#23]
```
/home/work/x2dhf/src/fpw86.f90:49:26:
        call prod2 (isiorb,psi(iborb),psi(iborb),wk1)
                          1
Error: Element of assumed-shaped or pointer array passed to array dummy argument ‘dx’ at (1)
/home/work/x2dhf/src/fpw86.f90:52:26:
        call prod2 (isiorb,psi(iborb),psi(iborb),wk2)
                          1
Error: Element of assumed-shaped or pointer array passed to array dummy argument ‘dx’ at (1)
```

as well as

```
/home/work/x2dhf/src/fockDFT.f90:94:91:
           call fpw86(psi,f4,wk8,wk9,wk10,wk11,wk12,wk13,excp,fock2,wk2,wk3,wk4,wk5,wk6,wk7)
                                                                                           1
Error: Actual argument for ‘psi’ cannot be an assumed-size array at (1)
```

**Comment by jacekkobus** [comment]
I wonder whether replacing 
call prod2 (isiorb,psi(iborb),psi(iborb),wk1)

by
    call copy (isiorb,psi(iborb),ione,wk7,ione)
    call prod2 (isiorb,w7,w7,wk1)

might help to avoid this error. I prefer the coding as it is because it avoids extra copying.

**Comment by susilehtola** [comment]
That didn't work, but just replacing
-    real (PREC), dimension(:) :: psi,f4,wk0,wk1,wk2,wk3,wk4,wk5,wk6,wk7, &
+    real (PREC), dimension(*) :: psi,f4,wk0,wk1,wk2,wk3,wk4,wk5,wk6,wk7, &
did the trick.

On the long term, assumed size arrays, i.e. (*), in the code should be replaced with assumed shape arrays, i.e. (:), (:,:) and so on, since they have bounds checks.
