### ISSUE TITLE
ini parameter in initGauss

### ISSUE THREAD

**Issue by susilehtola** [susilehtola/x2dhf#3]
The ini parameter, which appears to originate from discret.f90, is used in 
https://github.com/susilehtola/x2dhf/blob/master/src/initGauss.f90#L42

Does this make sense? @jacekkobus

**Comment by jacekkobus** [comment]
It seems that ini is needed in initGauss to guarantee that in case OED method is chosen only the highest orbital is initialized. Otherwise all orbitals are initialized from Gaussiam output.

**Comment by susilehtola** [comment]
OK, that clears it!
