### ISSUE TITLE
ioutmat in writeDisk4dd.f90

### ISSUE THREAD

**Issue by susilehtola** [susilehtola/x2dhf#4]
The parameter ioutmat is uninitialized in writeDisk4dd.f90 in functions check1dnu and check1dmu. @jacekkobus

**Comment by jacekkobus** [comment]
fixed in fix_2d_interpolation branch. writeDisk4dd is redundant (needed for producing data for another program I use).

**Comment by susilehtola** [comment]
Thanks! Fixed in master.
